create table aut_roles
(id                     number generated by default on null as identity not null,
name                    varchar2(50)                                    not null,
adb_id                  number                                          not null,
description             varchar2(200),
primary key(id)
);




create unique index aut_rle_i1 on aut_roles(name, adb_id);

--alter table aut_roles add constraint aut_rle_adb_fk_foreign key references aut_app_
create public synonym aut_roles for aut_roles;
