create table aut_rle_pve(
id                  number      generated by default on null as identity not null,
rle_id              number                                               not null,
pve_id              number                                               not null,
valid_from          date,
valid_until         date,
date_created        date,
user_created        varchar2(50),
date_modified       date,
user_modified       varchar2(50),
primary key(id));



alter table aut_rle_pve add constraint aut_rpe_pve_fk 
foreign key(pve_id) references aut_privileges(id);

alter table aut_rle_pve add constraint aut_rpe_rle_fl
foreign key(rle_id) references aut_roles(id);

create unique index aut_rpe_i1 on aut_rle_pve(rle_id, pve_id, valid_from);

