create table usr_role(
id              number generated by default on null as identity not null,
usr_id          number not null,
rle_id          number not null,
valid_from      date,
valid_until     date,
date_created    date,
user_created    varchar2(50),
date_modified   date,
user_modified   varchar2(50),
primary key(id));


alter table usr_role add constraint aut_ure_role_fk
foreign key(rle_id) references aut_roles(id);


alter table usr_role add constraint aut_ure_usr_fk
foreign key(usr_id) references aut_users(id);


create unique index aut_ure_i1 on aut_usr_rle(usr_id, rle_id, valid_from);
