create table aut_privileges(
id                      number                 generated by default on null as identity,
name                    varchar2(100)           not null,  
apex_page               number,
apex_component_name     varchar2(255),
read                    varchar2(1) default 'N' not null,
write                   varchar2(1) default 'N' not null,
adb_id                  number                  not null,
primary key(id)
);






create unique index aut_pve_i1 on aut_privileges(name, adb_id);


create unique index aut_pve_i2 on aut_privileges(name, apex_page, apex_component_name, adb_id);


create public synonym aut_privileges for aut_privileges;
