create table aut_users
(   id              number generated by default on null as identity                                   not null
,   username        varchar2(50)                        not null
,   password        varchar(256)                        
,   email           varchar2(100)
,   locked          varchar2(1) default 'N'             not null
,   expired         varchar(2)  default 'Y'             not null
,   logins_failed   number      default 0               not null
,   pw_last_upd     date        default sysdate         not null
,   date_created    date        default sysdate         not null
,   user_created    varchar2(50)                        not null
,   date_modified   date         default sysdate        
,   user_modified   varchar2(50)
,   last_call       date         default sysdate       not null
,   deleted         varchar2(1 char) default 'N'       not null
,   lang            varchar2(5)      default 'en'      not null
,   parent_user_id  number
,   primary key(id) 
);


create unique index aut_usr_i1 on aut_users(username);
create unique index aut_usr_i2 on aut_users(email);

alter table aut_users
    add constraint aut_usr_usr_fk
        foreign key (parent_user_id) references aut_users(id);
        
        alter table aut_users drop constraint aut_usr_usr_fk;
 
 create public synonym aut_users for aut_users;  
 
 